/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.Boleta;
import com.incloud.hcp.domain.Lote;
import com.incloud.hcp.domain.Venta;
import com.incloud.hcp.domain.response.VentaResponse;
import com.incloud.hcp.service.delta.VentaDeltaService;
import com.incloud.hcp.service.impl.VentaServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.ss.usermodel.Cell;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.util.List;

/**
 * A simple DTO Facility for Venta.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class VentaDeltaServiceImpl extends VentaServiceImpl implements VentaDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    /***********************/
    /* Metodos de Busqueda */
    /***********************/

    protected Sort setFindAll(Sort sort) {
        return sort;
    }

    protected Sort setFind(Venta req, ExampleMatcher matcher, Example<Venta> example, Sort sort) {
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<Venta> req, ExampleMatcher matcher, Example<Venta> example) {
        return;
    }

    protected List<Predicate> setAdicionalDeltaPredicate(List<Predicate> predicates, VentaResponse bean, CriteriaBuilder cb, CriteriaQuery<Venta> query,
            Root<Venta> root) throws Exception {

        Venta entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            Join<Venta, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
        
            if (Optional.ofNullable(entity.get<VariableManytoOne>().get<Atributo>()).isPresent()) {
                Join<Venta, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
                Predicate thirdCondition = cb.equal(from<ClaseManytoOne>.get("<Atributo>"), entity.get<ClaseManytoOne>().get<Atributo>());
                predicates.add(thirdCondition);
            }
            
        }
        query.orderBy(cb.desc(root.get("<campo entity>")));
        */
        return predicates;
    }

    protected Root<Venta> setAdicionalDeltaTotalPredicate(VentaResponse bean, Root<Venta> countRoot) throws Exception {
        Venta entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
                Join<Venta, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
            }
        }
        */
        return countRoot;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected String setValidacionesPrevias(Venta bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected Venta setCreate(Venta bean) throws Exception {
        return bean;
    }

    protected void setSave(Venta dto) throws Exception {
        return;
    }

    protected void setDelete(Integer id) throws Exception {

    }

    protected void setDeleteAll() throws Exception {

    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected Venta setUploadExcel(Cell currentCell, Venta venta, int contador) throws Exception {
        venta = super.setUploadExcel(currentCell, venta, contador);
        return venta;
    }

    protected String setSaveMasivo(Venta dto) throws Exception {
        return "";
    }

    protected List<Venta> setBeforeDeleteMasivo(List<Venta> listaDto) throws Exception {
        return listaDto;
    }

    protected void setAfterDeleteMasivo() throws Exception {
        return;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected void setDownloadExcelItem(Venta bean, HSSFRow dataRow) {

    }

    protected void setDownloadExcel(HSSFSheet sheet) {

    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    protected String setGraphDescripcionByLote(Lote idLote) {
        return idLote.getId().toString();
    }

    protected String setGraphPieChartTituloByLote() {
        return "Lote";
    }

    protected String setGraphBarChartTituloByLote() {
        return "Lote";
    }

    protected String setGraphDescripcionByBoleta(Boleta idBoleta) {
        return idBoleta.getId().toString();
    }

    protected String setGraphPieChartTituloByBoleta() {
        return "Boleta";
    }

    protected String setGraphBarChartTituloByBoleta() {
        return "Boleta";
    }

}
