/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.common.BindingErrorsResponse;
import com.incloud.hcp.common.graph.GraphBean;
import com.incloud.hcp.domain.Lote;
import com.incloud.hcp.domain.Producto;
import com.incloud.hcp.domain.response.LoteResponse;
import com.incloud.hcp.repository.delta.LoteDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import com.incloud.hcp.service.delta.LoteDeltaService;
import io.swagger.annotations.ApiOperation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

import javax.validation.Valid;
import java.net.URISyntaxException;
import java.util.Optional;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;

public abstract class LoteRest extends JPACustomRest<LoteResponse, Lote, Integer> {

    @Autowired
    protected LoteDeltaService loteDeltaService;

    @Autowired
    protected LoteDeltaRepository loteDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "Lote";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final Lote createInstance() {
        Lote lote = new Lote();
        return lote;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    /**
    * Contador de registros para el atributo idProducto.
    */
    @ApiOperation(value = "Contador de registros para el atributo idProducto", produces = "application/json")
    @PostMapping(value = "/countByProducto", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Long> countByProducto(@RequestBody @Valid Producto idProducto, BindingResult bindingResult) throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(errors.toJSON());
            }
            headers.add("errors", errors.toJSON());
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
        log.debug("Ingresando countByProducto");
        try {
            return Optional.ofNullable(this.loteDeltaService.countByProducto(idProducto)).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Genera Grafico de registros para el atributo idProducto.
    */
    @ApiOperation(value = "Genera Grafico de registros para el atributo idProducto", produces = "application/json")
    @GetMapping(value = "/graphByProducto", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GraphBean> graphByProducto() throws URISyntaxException {
        log.debug("Ingresando graphByProducto");
        try {
            return Optional.ofNullable(this.loteDeltaService.graphByProducto()).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            HttpHeaders headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

}
