/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.common.BindingErrorsResponse;
import com.incloud.hcp.common.graph.GraphBean;
import com.incloud.hcp.domain.Boleta;
import com.incloud.hcp.domain.Lote;
import com.incloud.hcp.domain.Venta;
import com.incloud.hcp.domain.response.VentaResponse;
import com.incloud.hcp.repository.delta.VentaDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import com.incloud.hcp.service.delta.VentaDeltaService;
import io.swagger.annotations.ApiOperation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

import javax.validation.Valid;
import java.net.URISyntaxException;
import java.util.Optional;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;

public abstract class VentaRest extends JPACustomRest<VentaResponse, Venta, Integer> {

    @Autowired
    protected VentaDeltaService ventaDeltaService;

    @Autowired
    protected VentaDeltaRepository ventaDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "Venta";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final Venta createInstance() {
        Venta venta = new Venta();
        return venta;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    /**
    * Contador de registros para el atributo idLote.
    */
    @ApiOperation(value = "Contador de registros para el atributo idLote", produces = "application/json")
    @PostMapping(value = "/countByLote", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Long> countByLote(@RequestBody @Valid Lote idLote, BindingResult bindingResult) throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(errors.toJSON());
            }
            headers.add("errors", errors.toJSON());
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
        log.debug("Ingresando countByLote");
        try {
            return Optional.ofNullable(this.ventaDeltaService.countByLote(idLote)).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Genera Grafico de registros para el atributo idLote.
    */
    @ApiOperation(value = "Genera Grafico de registros para el atributo idLote", produces = "application/json")
    @GetMapping(value = "/graphByLote", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GraphBean> graphByLote() throws URISyntaxException {
        log.debug("Ingresando graphByLote");
        try {
            return Optional.ofNullable(this.ventaDeltaService.graphByLote()).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            HttpHeaders headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Contador de registros para el atributo idBoleta.
    */
    @ApiOperation(value = "Contador de registros para el atributo idBoleta", produces = "application/json")
    @PostMapping(value = "/countByBoleta", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Long> countByBoleta(@RequestBody @Valid Boleta idBoleta, BindingResult bindingResult) throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(errors.toJSON());
            }
            headers.add("errors", errors.toJSON());
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
        log.debug("Ingresando countByBoleta");
        try {
            return Optional.ofNullable(this.ventaDeltaService.countByBoleta(idBoleta)).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Genera Grafico de registros para el atributo idBoleta.
    */
    @ApiOperation(value = "Genera Grafico de registros para el atributo idBoleta", produces = "application/json")
    @GetMapping(value = "/graphByBoleta", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GraphBean> graphByBoleta() throws URISyntaxException {
        log.debug("Ingresando graphByBoleta");
        try {
            return Optional.ofNullable(this.ventaDeltaService.graphByBoleta()).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            HttpHeaders headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

}
