/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.incloud.hcp.repository;

import com.incloud.hcp.domain.Boleta;
import com.incloud.hcp.domain.Lote;
import com.incloud.hcp.domain.Venta;
import com.incloud.hcp.repository._framework.JPACustomRepository;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.repository.NoRepositoryBean;
import org.springframework.data.repository.query.Param;

import java.util.List;

@NoRepositoryBean
public interface VentaRepository extends JPACustomRepository<Venta, Integer> {

    default List<Venta> findCompletePaginated(String query, int maxResults) {
        Venta probe = new Venta();
        ExampleMatcher matcher = ExampleMatcher.matching() //
        ;

        Page<Venta> page = this.findAll(Example.of(probe, matcher), PageRequest.of(0, maxResults));
        return page.getContent();
    }

    Long countByLote(@Param("idLote") Lote idLote);

    Long countByBoleta(@Param("idBoleta") Boleta idBoleta);

}
