/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package com.incloud.hcp.service.impl;

import com.incloud.hcp.common.enums.AppParametriaLabelEnum;
import com.incloud.hcp.common.enums.AppParametriaModuloEnum;
import com.incloud.hcp.common.excel.ExcelDefault;
import com.incloud.hcp.common.graph.GraphBarChart;
import com.incloud.hcp.common.graph.GraphBean;
import com.incloud.hcp.common.graph.GraphDataset;
import com.incloud.hcp.common.graph.GraphPieChart;
import com.incloud.hcp.domain.AppParametria;
import com.incloud.hcp.domain.Lote;
import com.incloud.hcp.domain.Producto;
import com.incloud.hcp.domain.response.LoteResponse;
import com.incloud.hcp.exception.ServiceException;
import com.incloud.hcp.repository.delta.AppParametriaDeltaRepository;
import com.incloud.hcp.repository.delta.LoteDeltaRepository;
import com.incloud.hcp.repository.delta.ProductoDeltaRepository;
import com.incloud.hcp.service.LoteService;
import com.incloud.hcp.service._framework.bean.BeanCargaMasivoDTO;
import com.incloud.hcp.service._framework.bean.BeanListaMasivoDTO;
import com.incloud.hcp.service._framework.impl.JPACustomServiceImpl;
import com.incloud.hcp.service.delta.ProductoDeltaService;
import com.incloud.hcp.service.requireNew.LoteRequireNewService;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.utils.Constants;
import com.incloud.hcp.utils.PredicateUtils;
import org.apache.commons.beanutils.BeanUtils;
import org.apache.commons.lang.StringUtils;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * A simple DTO Facility for Lote.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public abstract class LoteServiceImpl extends JPACustomServiceImpl<LoteResponse, Lote, Integer> implements LoteService {

    protected final String NAME_SHEET = "Lote";
    protected final String CONFIG_TITLE = "com/incloud/hcp/excel/LoteExcel.xml";
    private final Integer REGISTROS_COLOR = 10;

    @Autowired
    protected AppParametriaDeltaRepository appParametriaDeltaRepository;

    @Autowired
    protected LoteDeltaRepository loteDeltaRepository;

    @Autowired
    protected LoteRequireNewService loteRequireNewService;

    @Autowired
    protected ProductoDeltaService productoDeltaService;

    @Autowired
    protected ProductoDeltaRepository productoDeltaRepository;

    /*****************************/
    /* Metodos de Busqueda       */
    /*****************************/

    protected final ExampleMatcher setAbstractFind(ExampleMatcher matcher) {
        matcher = ExampleMatcher.matching() //
        ;
        return matcher;
    }

    protected abstract Sort setFindAll(Sort sort);

    protected abstract Sort setFind(Lote req, ExampleMatcher matcher, Example<Lote> example, Sort sort);

    protected abstract void setFindPaginated(PageRequestByExample<Lote> req, ExampleMatcher matcher, Example<Lote> example);

    protected final Lote setObtenerBeanResponse(LoteResponse bean) {
        return bean.getBean();
    }

    protected final Class<Lote> setObtenerClassBean() {
        return Lote.class;
    }

    protected List<Predicate> setAbstractPredicate(LoteResponse bean, CriteriaBuilder cb, Root<Lote> root) {
        List<Predicate> predicates = new ArrayList<>();
        Lote entity = bean.getBean();
        /* Obtener condiciones */
        PredicateUtils.addPredicates(predicates, bean.getIdCondicion(), "id", entity.getId(), cb, root);
        PredicateUtils.addPredicates(predicates, bean.getStockCondicion(), "stock", entity.getStock(), cb, root);
        PredicateUtils.addPredicates(predicates, bean.getPrecioCondicion(), "precio", entity.getPrecio(), cb, root);
        //PredicateUtils.addPredicates(predicates, bean.getIdProductoCondicion(), "idProducto", entity.getIdProducto(), cb, root);
        /* Obtener valores de Lista */
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "id", bean.getIdList(), cb, root);
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "stock", bean.getStockList(), cb, root);
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "precio", bean.getPrecioList(), cb, root);
        //PredicateUtils.addPredicatesListValorBean(predicates, "idProducto", bean.getIdProductoList(), cb, root);
        return predicates;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected final String validacionesPrevias(Lote bean) throws Exception {
        String mensaje = "";
        if (!Optional.of(bean.getStock()).isPresent()) {
            String msg = this.messageSource.getMessage("message.lote.stock.requerido", null, LocaleContextHolder.getLocale());
            mensaje += "* " + msg + "<br/>";
        }
        String msg = this.setValidacionesPrevias(bean);
        if (StringUtils.isNotBlank(msg)) {
            mensaje += "* " + msg + "<br/>";
        }
        return mensaje;
    }

    protected String setValidacionesPrevias(Lote bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected String validacionesPreviasCreate(Lote bean) throws Exception {
        String msg = null;
        Lote validar = null;
        return msg;
    }

    protected String validacionesPreviasSave(Lote bean) throws Exception {
        String msg = null;
        Lote validar = null;
        return msg;
    }

    protected Lote completarDatosBean(Lote bean) throws Exception {
        BigDecimal data = new BigDecimal(0.00);
        if (Optional.ofNullable(bean.getPrecio()).isPresent()) {
            bean.setPrecio(bean.getPrecio().setScale(2, BigDecimal.ROUND_HALF_UP));
        }
        bean = this.setCompletarDatosBean(bean);
        return bean;
    }

    protected Lote setCompletarDatosBean(Lote bean) throws Exception {
        return bean;
    }

    protected final Lote setAbstractCreate(Lote dto) throws Exception {
        Lote bean = new Lote();
        bean = (Lote) BeanUtils.cloneBean(dto);
        return bean;
    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected Lote setUploadExcel(Cell currentCell, Lote lote, int contador) throws Exception {
        Double valorDouble = new Double(0);
        BigDecimal valorDecimal = new BigDecimal(0);
        Boolean valorBoolean = new Boolean(true);
        String valorCadena = "";
        switch (contador) {
        case 1:
            try {
                valorDouble = new Double(currentCell.getNumericCellValue());
                lote.setStock(valorDouble.intValue());
            } catch (Exception e) {
                throw new ServiceException("Valor Campo stock está en formato incorrecto");
            }
            break;
        case 2:
            try {
                valorDecimal = new BigDecimal(currentCell.getNumericCellValue());
                lote.setPrecio(valorDecimal);
            } catch (Exception e) {
                throw new ServiceException("Valor Campo precio está en formato incorrecto");
            }
            break;
        default:
            break;
        }
        return lote;
    }

    protected AppParametria setObtenerRegistroConfiguracionUploadExcel() {
        AppParametria appParametriaData = this.appParametriaDeltaRepository.getByModuloAndLabelAndStatus(AppParametriaModuloEnum.CARGA_EXCEL.getEstado(),
                AppParametriaLabelEnum.INICIO_REGISTRO_DATA.getEstado(), Constants.ESTADO_ACTIVO);
        return appParametriaData;
    }

    protected Lote setInicializarBeanUpdateExcel() {
        Lote bean = new Lote();
        bean.setId(null);
        return bean;
    }

    protected final Integer setObtenerId(Lote bean) {
        return bean.getId();
    }

    /************************/
    /* Instancia de Bean    */
    /************************/

    protected final Lote createInstance() {
        Lote lote = new Lote();
        return lote;
    }

    protected final BeanCargaMasivoDTO<Lote> createInstanceMasivoDTO() {
        BeanCargaMasivoDTO<Lote> beanCargaMasivoDTO = new BeanCargaMasivoDTO<Lote>();
        return beanCargaMasivoDTO;

    }

    protected final BeanListaMasivoDTO<BeanCargaMasivoDTO<Lote>> createInstanceListaMasivoDTO() {
        BeanListaMasivoDTO<BeanCargaMasivoDTO<Lote>> beanCargaMasivoDTOBeanListaMasivoDTO = new BeanListaMasivoDTO<BeanCargaMasivoDTO<Lote>>();
        return beanCargaMasivoDTOBeanListaMasivoDTO;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected String devuelveNombreSheet() {
        return this.NAME_SHEET;
    }

    protected String devuelveListaHeaderExcelXML() {
        return this.CONFIG_TITLE;
    }

    protected int setAbstractDownloadExcel(Lote bean, HSSFRow dataRow) {
        int contador = 0;
        ExcelDefault.setValueCell(bean.getId(), dataRow.createCell(contador));
        contador++;
        ExcelDefault.setValueCell(bean.getStock(), dataRow.createCell(contador));
        contador++;
        ExcelDefault.setValueCell(bean.getPrecio(), dataRow.createCell(contador));
        contador++;
        return contador;
    }

    protected int setAbstractDownloadExcelSXLSX(Lote bean, Row dataRow, List<CellStyle> cellStyleList) {
        int contador = 0;
        ExcelDefault.setValueCell(bean.getId(), dataRow.createCell(contador), "I", cellStyleList);
        contador++;
        ExcelDefault.setValueCell(bean.getStock(), dataRow.createCell(contador), "I", cellStyleList);
        contador++;
        ExcelDefault.setValueCell(bean.getPrecio(), dataRow.createCell(contador), "N", cellStyleList);
        contador++;
        return contador;
    }

    protected String setAbstractGenerateInsertExcelSXLSX(Lote bean) {
        String fechaS = "";
        String sqlInsert = "INSERT INTO LOTE(";
        sqlInsert = sqlInsert + "ID_LOTE" + ", ";
        sqlInsert = sqlInsert + "STOCK" + ", ";
        sqlInsert = sqlInsert + "PRECIO" + ", ";
        sqlInsert = sqlInsert + "ID_PRODUCTO" + ")";
        sqlInsert = sqlInsert + " VALUES (";
        sqlInsert = sqlInsert + bean.getId() + ", ";
        sqlInsert = sqlInsert + bean.getStock() + ", ";
        sqlInsert = sqlInsert + bean.getPrecio() + ", ";
        sqlInsert = sqlInsert + bean.getIdProducto().getId();
        sqlInsert = sqlInsert + " );";
        return sqlInsert;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    public Long countByProducto(Producto idProducto) {
        return this.loteDeltaRepository.countByProducto(idProducto);
    }

    public GraphBean graphByProducto() {
        List<Producto> lista = this.productoDeltaRepository.findAll();
        if (lista == null || lista.size() <= 0) {
            return null;
        }
        GraphBean graphBean = new GraphBean();

        /* Obteniendo Pie Chart */
        GraphPieChart graphPieChart = new GraphPieChart();
        GraphDataset graphDataset = new GraphDataset();
        GraphDataset[] listaGraphDataset = new GraphDataset[1];
        Long[] data = new Long[lista.size()];
        String[] labels = new String[lista.size()];
        String[] backgroundColor = new String[lista.size()];
        String[] hoverBackgroundColor = new String[lista.size()];
        String[] borderColor = new String[lista.size()];
        String[] hoverBorderColor = new String[lista.size()];
        int contador = 0;
        int contadorColor = 0;
        for (Producto bean : lista) {
            Long valor = this.loteDeltaRepository.countByProducto(bean);
            String descripcion = this.setGraphDescripcionByProducto(bean);
            data[contador] = valor;
            labels[contador] = descripcion;
            backgroundColor[contador] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBackgroundColor[contador] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];
            borderColor[contador] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBorderColor[contador] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];
            contador++;
            contadorColor++;
            if (contadorColor >= REGISTROS_COLOR) {
                contadorColor = 1;
            }
        }
        String titulo = this.setGraphPieChartTituloByProducto();
        graphDataset.setLabel(titulo);
        graphDataset.setData(data);
        graphDataset.setBackgroundColor(backgroundColor);
        graphDataset.setHoverBackgroundColor(hoverBackgroundColor);
        listaGraphDataset[0] = graphDataset;
        graphPieChart.setDatasets(listaGraphDataset);
        graphPieChart.setLabels(labels);
        graphBean.setPiechart(graphPieChart);

        GraphBarChart graphBarChart = new GraphBarChart();
        GraphDataset[] listaGraphDatasetBar = new GraphDataset[lista.size()];
        String[] labelsBar = new String[1];
        labelsBar[0] = this.setGraphBarChartTituloByProducto();
        contador = 0;
        contadorColor = 0;
        for (Producto bean : lista) {
            Long valor = this.loteDeltaRepository.countByProducto(bean);
            String descripcion = this.setGraphDescripcionByProducto(bean);
            GraphDataset graphDatasetBar = new GraphDataset();
            Long[] dataBar = new Long[1];

            String[] backgroundColorBar = new String[1];
            String[] hoverBackgroundColorBar = new String[1];
            String[] borderColorBar = new String[1];
            String[] hoverBorderColorBar = new String[1];

            dataBar[0] = valor;
            backgroundColorBar[0] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBackgroundColorBar[0] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];
            borderColorBar[0] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBorderColorBar[0] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];

            graphDatasetBar.setLabel(descripcion);
            graphDatasetBar.setData(dataBar);
            graphDatasetBar.setBackgroundColor(backgroundColorBar);
            graphDatasetBar.setHoverBackgroundColor(hoverBackgroundColorBar);
            graphDatasetBar.setBorderColor(borderColorBar);
            graphDatasetBar.setHoverBorderColor(hoverBorderColorBar);
            listaGraphDatasetBar[contador] = graphDatasetBar;

            contador++;
            contadorColor++;
            if (contadorColor >= REGISTROS_COLOR) {
                contadorColor = 1;
            }

        }
        graphBarChart.setDatasets(listaGraphDatasetBar);
        graphBarChart.setLabels(labelsBar);
        graphBean.setBarchart(graphBarChart);
        return graphBean;
    }

    protected String setGraphDescripcionByProducto(Producto idProducto) {
        return idProducto.getId().toString();
    }

    protected String setGraphPieChartTituloByProducto() {
        return "Producto";
    }

    protected String setGraphBarChartTituloByProducto() {
        return "Producto";
    }

}
