/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.google.common.base.MoreObjects;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "producto")
//@Audited
//@AuditTable("_audi_PRODUCTO")
public class Producto extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(Producto.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Integer id;
    private String descripcion;
    private String presentacion;

    @Override
    public String entityClassName() {
        return Producto.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "id_producto", precision = 5)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_producto")
    @Id
    @SequenceGenerator(name = "seq_producto", sequenceName = "seq_producto", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Producto id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [descripcion] ------------------------

    @NotEmpty(message = "{message.producto.descripcion.requerido}")
    @Size(max = 255, message = "{message.producto.descripcion.sizeMax} {max} {message.caracter}")
    @Column(name = "descripcion", nullable = false)
    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Producto descripcion(String descripcion) {
        setDescripcion(descripcion);
        return this;
    }
    // -- [presentacion] ------------------------

    @NotEmpty(message = "{message.producto.presentacion.requerido}")
    @Size(max = 2500, message = "{message.producto.presentacion.sizeMax} {max} {message.caracter}")
    @Column(name = "presentacion", nullable = false, length = 2500)
    public String getPresentacion() {
        return presentacion;
    }

    public void setPresentacion(String presentacion) {
        this.presentacion = presentacion;
    }

    public Producto presentacion(String presentacion) {
        setPresentacion(presentacion);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Producto withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Producto && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Producto instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("descripcion", getDescripcion()) //
                .add("presentacion", getPresentacion()) //
                .toString();
    }
}
