/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityResponse.java.e.vm
 */
package com.incloud.hcp.domain.response;

import com.incloud.hcp.domain.BaseResponseDomain;
import com.incloud.hcp.domain.Boleta;
import com.incloud.hcp.domain.Lote;
import com.incloud.hcp.domain.Venta;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.util.Date;
import java.util.List;

/**
 * Simple Interface for Venta.
 */
@Data
@ToString
@EqualsAndHashCode
public class VentaResponse extends BaseResponseDomain<Venta> {

    /****************************/
    /* Variables de Condiciones */
    /****************************/

    private String idCondicion;
    private String fechaVentaCondicion;
    //private String idLoteCondicion;
    //private String idBoletaCondicion;

    /****************************/
    /* Variables Listas         */
    /****************************/

    private List<Integer> idList;
    private List<Date> fechaVentaList;
    private List<Lote> idLoteList;
    private List<Boleta> idBoletaList;

}
